name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  validate-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release

  validate-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
      - name: Lint
        run: cargo clippy -- -D warnings
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
